name = "rpc_json_server"
version = "0.1.0"

licences = ["Apache-2.0"]
description = "A RPC JSON server written in Gleam!"

repository = { type = "github", user = "martinfojtik", repo = "rpc-json-server-gleam" }

[dependencies]
gleam_stdlib = "~> 0.65"
gleam_http = "~> 4.3"
gleam_erlang = "~> 1.3"
wisp = ">= 2.0.0 and < 3.0.0"
mist = ">= 5.0.0 and < 6.0.0"
envoy = ">= 1.0.2 and < 2.0.0"

[dev-dependencies]
gleeunit = "~> 1.6"
